name: Production Docker Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g., latest, dev, v1.2.3)'
        required: true
        default: '1.18.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code with submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        use: true

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build \
          --platform linux/amd64,linux/arm64,linux/arm/v7,linux/ppc64le,linux/s390x \
          -t emgi2/pepecoin-electrum:${{ github.event.inputs.tag }} \
          -t emgi2/pepecoin-electrum:latest \
          --push .
